name: 'publish'
on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    outputs:
      release_id: ${{ steps.create-release.outputs.releaseId }}
      release_url: ${{ steps.create-release.outputs.releaseHtmlUrl }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Install app dependencies and build
        run: yarn && yarn build
        env:
          FA_TOKEN: ${{ secrets.FA_TOKEN }}
      - name: Create release
        id: create-release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FA_TOKEN: ${{ secrets.FA_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        with:
          tagName: ssh-app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'SSH App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
      - name: Generate updater json
        run: yarn updater:gen
        env:
          FA_TOKEN: ${{ secrets.FA_TOKEN }}
          GITHUB_WORKSPACE: ${{ github.workspace }}
          RELEASE_ID: ${{ needs.create-release.outputs.release_id }}
          RELEASE_URL: ${{ needs.create-release.outputs.release_url }}
      - name: Deploy updater JSON
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.UPDATER_ID }}
          file_path: updater.json
